version: '3.7'

services:
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 5000:80
    depends_on:
      - web
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 5000
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    depends_on:
      - db
  db:
    image: edoburu/pgbouncer
    environment:
      - MAX_CLIENT_CONN=4000
      - DEFAULT_POOL_SIZE=30
      - MIN_POOL_SIZE=1
      - POOL_MODE=transaction
      - DB_HOST=pg
    env_file:
      - ./.env.prod.pgbouncer
    depends_on:
      - pg
  pg:
    build: ./services/pg
    command: postgres -c config_file=/etc/postgresql.conf
    #volumes:
        #- postgres_data:/var/lib/postgresql/data/
        #- postgres_fastdata:/fastdata
        #- /data/volumes/novichenko_18jan:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  static_volume:
      #postgres_fastdata:
